language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.2.0
  - 2.2.4
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_stable.gemfile
script: "bundle exec rake spec"
addons:
  code_climate:
    repo_token: 344f2a60a2920e96f71877b87829836b01a44e1e94463cde54e2c54e8f389f79
